from typing import Protocol

from flowr.domain.flow_definition import Flow


class FlowExporter(Protocol):
    def format_name(self) -> str: ...
    def description(self) -> str: ...
    def supports_directory(self) -> bool: ...
    def add_arguments(self, parser: object) -> None: ...
    def export(self, flow: Flow, options: dict) -> str: ...
    def export_directory(self, flows: list[tuple[str, Flow]], options: dict) -> str: ...
